[package]
name = "net-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.5.6"
sysinfo = "0.29.10"
tokio = { version = "1.40", features = ["full"] }

[features]
desktop = ["dioxus/desktop"]
