[package]
name = "net-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
sysinfo = "0.29.10"
tokio = { version = "1", features = ["full"] }
