[package]
name = "net-monitor"
version = "0.2.0"
edition = "2021"

[dependencies]
dioxus = "0.5.6"
sysinfo = { version = "0.32", default-features = false, features = ["network"] }
tokio = { version = "1.40", features = ["full"] }

[features]
desktop = ["dioxus/desktop"]
